### ISSUE TITLE
RFC XML generation is broken in this document due to https://github.com/metanorma/metanorma-ietf/issues/22

### ISSUE THREAD

**Issue by ronaldtse** [CalConnect/csd-vpoll#2]
RFC XML generation is broken in this document due to https://github.com/metanorma/metanorma-ietf/issues/22

* Once that is fixed, we need to fix this document. 
* Or we fix this document somehow so that the RFC XML output doesn't break.

ping @opoudjis

**Comment by opoudjis** [comment]
Fixed. @ronaldtse please close this ticket.
