### ISSUE TITLE
Deployment: index page doesn’t show RFC versions

### ISSUE THREAD

**Issue by ronaldtse** [CalConnect/csd-vpoll#4]
The index page should show RFCs. Right now it only shows the CC version. Reason why RFC versions are missing is due to the command “relaton concatenate” not being able to obtain the RXL files. Ping @andrew2net

**Comment by andrew2net** [comment]
@ronaldtse I go the error:
```
Error: No such file or directory @ rb_sysopen - /var/folders/qf/c8zl30p57pq5p7n1l5znydl80000gn/T/sources/draft-calext-vpoll.txt20190619-9318-1gtg6vf,
Not sure what to run? try: metanorma help
make: *** [sources/draft-calext-vpoll.xml] Error 2
```
Is the error related to this issue?

**Comment by ronaldtse** [comment]
@andrew2net I'm not sure why you're having this problem. How are you executing the `metanorma` command?

**Comment by andrew2net** [comment]
I run `make clean all`

**Comment by andrew2net** [comment]
@ronaldtse It works with docker. How can I check if the index page shows RFC?

**Comment by andrew2net** [comment]
@ronaldtse maybe it helps. I noteced an error in log I didn't before:
```
[metanorma] Error: nits format is not supported for this standard.
```
it is in log before the error I posted erarly
> ```
> Error: No such file or directory @ rb_sysopen - /var/folders/qf/c8zl30p57pq5p7n1l5znydl80000gn/T/sources/draft-calext-vpoll.txt20190619-9318-1gtg6vf,
> Not sure what to run? try: metanorma help
> make: *** [sources/draft-calext-vpoll.xml] Error 2
> ```

**Comment by andrew2net** [comment]
@ronaldtse I'm not able to run metanorma on my comp. However if I put `draft-celi-acvp-sha-00.xml` into `documents` and run the command:
```
bundle exec relaton concatenate -t "$(yq r metanorma.yml relaton.collection.name)" -g "$(yq r metanorma.yml relaton.collection.organization)" documents documents.rxl
```
It produces `documents.rxl`. But I see related changes in `relaton-cli` aren't released. Be sure you install `relaton-cli` form GitHub repo.

**Comment by ronaldtse** [comment]
@andrew2net so we need to update relaton-ietf and also relaton-cli to make this work.

**Comment by andrew2net** [comment]
@ronaldtse ok, I will

**Comment by ronaldtse** [comment]
@andrew2net I've pushed this 832a466 so the index now generates. It now gives the HTML/XML versions but doesn't make the link for the TXT version. Will post an issue in `relaton-cli`.

**Comment by ronaldtse** [comment]
https://github.com/metanorma/relaton-cli/issues/53 is the remaining issue. Closing this.
